# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.rerun_workflow_request import RerunWorkflowRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestRerunWorkflowRequest(unittest.TestCase):
    """RerunWorkflowRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRerunWorkflowRequest(self):
        """Test RerunWorkflowRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.rerun_workflow_request.RerunWorkflowRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
