# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.task_def import TaskDef  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskDef(unittest.TestCase):
    """TaskDef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskDef(self):
        """Test TaskDef"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.task_def.TaskDef()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
