# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.action import Action  # noqa: E501
from swagger_client.rest import ApiException


class TestAction(unittest.TestCase):
    """Action unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAction(self):
        """Test Action"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.action.Action()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
