import pprint
import re  # noqa: F401
from dataclasses import dataclass, field, InitVar
from typing import Dict, List, Optional, Any, TypeVar, Generic, Union

import six
from deprecated import deprecated

T = TypeVar('T')


@dataclass
class BulkResponse(Generic[T]):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bulk_error_results': 'dict(str, str)',
        'bulk_successful_results': 'list[str]',
        'message': 'str'
    }

    attribute_map = {
        'bulk_error_results': 'bulkErrorResults',
        'bulk_successful_results': 'bulkSuccessfulResults',
        'message': 'message'
    }

    bulk_error_results: InitVar[Optional[Dict[str, str]]] = None
    bulk_successful_results: InitVar[Optional[List[T]]] = None

    _bulk_error_results: Optional[Dict[str, str]] = field(default=None, init=False)
    _bulk_successful_results: Optional[List[T]] = field(default=None, init=False)
    _message: str = field(default="Bulk Request has been processed.", init=False)

    def __init__(self, bulk_error_results=None, bulk_successful_results=None):  # noqa: E501
        """BulkResponse - a model defined in Swagger"""  # noqa: E501
        self._bulk_error_results = None
        self._bulk_successful_results = None
        self._message = "Bulk Request has been processed."
        self.discriminator = None
        if bulk_error_results is not None:
            self.bulk_error_results = bulk_error_results
        if bulk_successful_results is not None:
            self.bulk_successful_results = bulk_successful_results

    def __post_init__(self, bulk_error_results, bulk_successful_results):
        """Initialize fields after dataclass initialization"""
        if bulk_error_results is not None:
            self.bulk_error_results = bulk_error_results
        if bulk_successful_results is not None:
            self.bulk_successful_results = bulk_successful_results

    @property
    def bulk_error_results(self) -> Optional[Dict[str, str]]:
        """Gets the bulk_error_results of this BulkResponse.  # noqa: E501

        Key - entityId Value - error message processing this entity

        :return: The bulk_error_results of this BulkResponse.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._bulk_error_results

    @bulk_error_results.setter
    def bulk_error_results(self, bulk_error_results: Optional[Dict[str, str]]):
        """Sets the bulk_error_results of this BulkResponse.

        Key - entityId Value - error message processing this entity

        :param bulk_error_results: The bulk_error_results of this BulkResponse.  # noqa: E501
        :type: dict(str, str)
        """

        self._bulk_error_results = bulk_error_results

    @property
    def bulk_successful_results(self) -> Optional[List[T]]:
        """Gets the bulk_successful_results of this BulkResponse.  # noqa: E501


        :return: The bulk_successful_results of this BulkResponse.  # noqa: E501
        :rtype: list[T]
        """
        return self._bulk_successful_results

    @bulk_successful_results.setter
    def bulk_successful_results(self, bulk_successful_results: Optional[List[T]]):
        """Sets the bulk_successful_results of this BulkResponse.


        :param bulk_successful_results: The bulk_successful_results of this BulkResponse.  # noqa: E501
        :type: list[str]
        """

        self._bulk_successful_results = bulk_successful_results

    @property
    def message(self) -> str:
        """Gets the message of this BulkResponse.  # noqa: E501


        :return: The message of this BulkResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    def append_success_response(self, result: T):
        """Appends a successful result to bulk_successful_results.  # noqa: E501

        :param result: The result to append to bulk_successful_results
        """
        if self._bulk_successful_results is None:
            self._bulk_successful_results = []
        self._bulk_successful_results.append(result)

    def append_failed_response(self, id: str, error_message: str):
        """Appends a failed result to bulk_error_results.  # noqa: E501

        :param id: The entity ID that failed
        :param error_message: The error message for the failed entity
        """
        if self._bulk_error_results is None:
            self._bulk_error_results = {}
        self._bulk_error_results[id] = error_message

    def to_dict(self) -> Dict[str, Any]:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BulkResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, BulkResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other