import pprint
import re  # noqa: F401

import six

class SaveScheduleRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_by': 'str',
        'cron_expression': 'str',
        'name': 'str',
        'paused': 'bool',
        'run_catchup_schedule_instances': 'bool',
        'schedule_end_time': 'int',
        'schedule_start_time': 'int',
        'start_workflow_request': 'StartWorkflowRequest',
        'updated_by': 'str'
    }

    attribute_map = {
        'created_by': 'createdBy',
        'cron_expression': 'cronExpression',
        'name': 'name',
        'paused': 'paused',
        'run_catchup_schedule_instances': 'runCatchupScheduleInstances',
        'schedule_end_time': 'scheduleEndTime',
        'schedule_start_time': 'scheduleStartTime',
        'start_workflow_request': 'startWorkflowRequest',
        'updated_by': 'updatedBy'
    }

    def __init__(self, created_by=None, cron_expression=None, name=None, paused=None, run_catchup_schedule_instances=None, schedule_end_time=None, schedule_start_time=None, start_workflow_request=None, updated_by=None):  # noqa: E501
        """SaveScheduleRequest - a model defined in Swagger"""  # noqa: E501
        self._created_by = None
        self._cron_expression = None
        self._name = None
        self._paused = None
        self._run_catchup_schedule_instances = None
        self._schedule_end_time = None
        self._schedule_start_time = None
        self._start_workflow_request = None
        self._updated_by = None
        self.discriminator = None
        if created_by is not None:
            self.created_by = created_by
        self.cron_expression = cron_expression
        self.name = name
        if paused is not None:
            self.paused = paused
        if run_catchup_schedule_instances is not None:
            self.run_catchup_schedule_instances = run_catchup_schedule_instances
        if schedule_end_time is not None:
            self.schedule_end_time = schedule_end_time
        if schedule_start_time is not None:
            self.schedule_start_time = schedule_start_time
        self.start_workflow_request = start_workflow_request
        if updated_by is not None:
            self.updated_by = updated_by

    @property
    def created_by(self):
        """Gets the created_by of this SaveScheduleRequest.  # noqa: E501


        :return: The created_by of this SaveScheduleRequest.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this SaveScheduleRequest.


        :param created_by: The created_by of this SaveScheduleRequest.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def cron_expression(self):
        """Gets the cron_expression of this SaveScheduleRequest.  # noqa: E501


        :return: The cron_expression of this SaveScheduleRequest.  # noqa: E501
        :rtype: str
        """
        return self._cron_expression

    @cron_expression.setter
    def cron_expression(self, cron_expression):
        """Sets the cron_expression of this SaveScheduleRequest.


        :param cron_expression: The cron_expression of this SaveScheduleRequest.  # noqa: E501
        :type: str
        """
        if cron_expression is None:
            raise ValueError("Invalid value for `cron_expression`, must not be `None`")  # noqa: E501

        self._cron_expression = cron_expression

    @property
    def name(self):
        """Gets the name of this SaveScheduleRequest.  # noqa: E501


        :return: The name of this SaveScheduleRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SaveScheduleRequest.


        :param name: The name of this SaveScheduleRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def paused(self):
        """Gets the paused of this SaveScheduleRequest.  # noqa: E501


        :return: The paused of this SaveScheduleRequest.  # noqa: E501
        :rtype: bool
        """
        return self._paused

    @paused.setter
    def paused(self, paused):
        """Sets the paused of this SaveScheduleRequest.


        :param paused: The paused of this SaveScheduleRequest.  # noqa: E501
        :type: bool
        """

        self._paused = paused

    @property
    def run_catchup_schedule_instances(self):
        """Gets the run_catchup_schedule_instances of this SaveScheduleRequest.  # noqa: E501


        :return: The run_catchup_schedule_instances of this SaveScheduleRequest.  # noqa: E501
        :rtype: bool
        """
        return self._run_catchup_schedule_instances

    @run_catchup_schedule_instances.setter
    def run_catchup_schedule_instances(self, run_catchup_schedule_instances):
        """Sets the run_catchup_schedule_instances of this SaveScheduleRequest.


        :param run_catchup_schedule_instances: The run_catchup_schedule_instances of this SaveScheduleRequest.  # noqa: E501
        :type: bool
        """

        self._run_catchup_schedule_instances = run_catchup_schedule_instances

    @property
    def schedule_end_time(self):
        """Gets the schedule_end_time of this SaveScheduleRequest.  # noqa: E501


        :return: The schedule_end_time of this SaveScheduleRequest.  # noqa: E501
        :rtype: int
        """
        return self._schedule_end_time

    @schedule_end_time.setter
    def schedule_end_time(self, schedule_end_time):
        """Sets the schedule_end_time of this SaveScheduleRequest.


        :param schedule_end_time: The schedule_end_time of this SaveScheduleRequest.  # noqa: E501
        :type: int
        """

        self._schedule_end_time = schedule_end_time

    @property
    def schedule_start_time(self):
        """Gets the schedule_start_time of this SaveScheduleRequest.  # noqa: E501


        :return: The schedule_start_time of this SaveScheduleRequest.  # noqa: E501
        :rtype: int
        """
        return self._schedule_start_time

    @schedule_start_time.setter
    def schedule_start_time(self, schedule_start_time):
        """Sets the schedule_start_time of this SaveScheduleRequest.


        :param schedule_start_time: The schedule_start_time of this SaveScheduleRequest.  # noqa: E501
        :type: int
        """

        self._schedule_start_time = schedule_start_time

    @property
    def start_workflow_request(self):
        """Gets the start_workflow_request of this SaveScheduleRequest.  # noqa: E501


        :return: The start_workflow_request of this SaveScheduleRequest.  # noqa: E501
        :rtype: StartWorkflowRequest
        """
        return self._start_workflow_request

    @start_workflow_request.setter
    def start_workflow_request(self, start_workflow_request):
        """Sets the start_workflow_request of this SaveScheduleRequest.


        :param start_workflow_request: The start_workflow_request of this SaveScheduleRequest.  # noqa: E501
        :type: StartWorkflowRequest
        """
        if start_workflow_request is None:
            raise ValueError("Invalid value for `start_workflow_request`, must not be `None`")  # noqa: E501

        self._start_workflow_request = start_workflow_request

    @property
    def updated_by(self):
        """Gets the updated_by of this SaveScheduleRequest.  # noqa: E501


        :return: The updated_by of this SaveScheduleRequest.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this SaveScheduleRequest.


        :param updated_by: The updated_by of this SaveScheduleRequest.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SaveScheduleRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SaveScheduleRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
