import pprint
import re  # noqa: F401
import six
from dataclasses import dataclass, field, InitVar
from typing import Dict, Any, Optional
from enum import Enum


class WorkflowSignalReturnStrategy(Enum):
    """Enum for workflow signal return strategy"""
    TARGET_WORKFLOW = "TARGET_WORKFLOW"
    BLOCKING_WORKFLOW = "BLOCKING_WORKFLOW"
    BLOCKING_TASK = "BLOCKING_TASK"
    BLOCKING_TASK_INPUT = "BLOCKING_TASK_INPUT"


@dataclass
class SignalResponse:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    _response_type: Optional[str] = field(default=None, init=False)
    _target_workflow_id: Optional[str] = field(default=None, init=False)
    _target_workflow_status: Optional[str] = field(default=None, init=False)
    _request_id: Optional[str] = field(default=None, init=False)
    _workflow_id: Optional[str] = field(default=None, init=False)
    _correlation_id: Optional[str] = field(default=None, init=False)
    _input: Optional[Dict[str, Any]] = field(default=None, init=False)
    _output: Optional[Dict[str, Any]] = field(default=None, init=False)

    response_type: InitVar[Optional[str]] = None
    target_workflow_id: InitVar[Optional[str]] = None
    target_workflow_status: InitVar[Optional[str]] = None
    request_id: InitVar[Optional[str]] = None
    workflow_id: InitVar[Optional[str]] = None
    correlation_id: InitVar[Optional[str]] = None
    input: InitVar[Optional[Dict[str, Any]]] = None
    output: InitVar[Optional[Dict[str, Any]]] = None

    swagger_types = {
        'response_type': 'str',
        'target_workflow_id': 'str',
        'target_workflow_status': 'str',
        'request_id': 'str',
        'workflow_id': 'str',
        'correlation_id': 'str',
        'input': 'dict(str, object)',
        'output': 'dict(str, object)'
    }

    attribute_map = {
        'response_type': 'responseType',
        'target_workflow_id': 'targetWorkflowId',
        'target_workflow_status': 'targetWorkflowStatus',
        'request_id': 'requestId',
        'workflow_id': 'workflowId',
        'correlation_id': 'correlationId',
        'input': 'input',
        'output': 'output'
    }

    def __init__(self, response_type=None, target_workflow_id=None, target_workflow_status=None,
                 request_id=None, workflow_id=None, correlation_id=None, input=None, output=None):  # noqa: E501
        """SignalResponse - a model defined in Swagger"""  # noqa: E501
        self._response_type = None
        self._target_workflow_id = None
        self._target_workflow_status = None
        self._request_id = None
        self._workflow_id = None
        self._correlation_id = None
        self._input = None
        self._output = None
        self.discriminator = None

        if response_type is not None:
            self.response_type = response_type
        if target_workflow_id is not None:
            self.target_workflow_id = target_workflow_id
        if target_workflow_status is not None:
            self.target_workflow_status = target_workflow_status
        if request_id is not None:
            self.request_id = request_id
        if workflow_id is not None:
            self.workflow_id = workflow_id
        if correlation_id is not None:
            self.correlation_id = correlation_id
        if input is not None:
            self.input = input
        if output is not None:
            self.output = output

    def __post_init__(self, response_type, target_workflow_id, target_workflow_status, request_id,
                      workflow_id, correlation_id, input, output):
        if response_type is not None:
            self.response_type = response_type
        if target_workflow_id is not None:
            self.target_workflow_id = target_workflow_id
        if target_workflow_status is not None:
            self.target_workflow_status = target_workflow_status
        if request_id is not None:
            self.request_id = request_id
        if workflow_id is not None:
            self.workflow_id = workflow_id
        if correlation_id is not None:
            self.correlation_id = correlation_id
        if input is not None:
            self.input = input
        if output is not None:
            self.output = output

    @property
    def response_type(self):
        """Gets the response_type of this SignalResponse.  # noqa: E501


        :return: The response_type of this SignalResponse.  # noqa: E501
        :rtype: str
        """
        return self._response_type

    @response_type.setter
    def response_type(self, response_type):
        """Sets the response_type of this SignalResponse.


        :param response_type: The response_type of this SignalResponse.  # noqa: E501
        :type: str
        """
        allowed_values = ["TARGET_WORKFLOW", "BLOCKING_WORKFLOW", "BLOCKING_TASK", "BLOCKING_TASK_INPUT"]  # noqa: E501
        if response_type is not None and response_type not in allowed_values:
            raise ValueError(
                "Invalid value for `response_type` ({0}), must be one of {1}"  # noqa: E501
                .format(response_type, allowed_values)
            )

        self._response_type = response_type

    @property
    def target_workflow_id(self):
        """Gets the target_workflow_id of this SignalResponse.  # noqa: E501


        :return: The target_workflow_id of this SignalResponse.  # noqa: E501
        :rtype: str
        """
        return self._target_workflow_id

    @target_workflow_id.setter
    def target_workflow_id(self, target_workflow_id):
        """Sets the target_workflow_id of this SignalResponse.


        :param target_workflow_id: The target_workflow_id of this SignalResponse.  # noqa: E501
        :type: str
        """

        self._target_workflow_id = target_workflow_id

    @property
    def target_workflow_status(self):
        """Gets the target_workflow_status of this SignalResponse.  # noqa: E501


        :return: The target_workflow_status of this SignalResponse.  # noqa: E501
        :rtype: str
        """
        return self._target_workflow_status

    @target_workflow_status.setter
    def target_workflow_status(self, target_workflow_status):
        """Sets the target_workflow_status of this SignalResponse.


        :param target_workflow_status: The target_workflow_status of this SignalResponse.  # noqa: E501
        :type: str
        """
        allowed_values = ["RUNNING", "COMPLETED", "FAILED", "TIMED_OUT", "TERMINATED", "PAUSED"]  # noqa: E501
        if target_workflow_status is not None and target_workflow_status not in allowed_values:
            raise ValueError(
                "Invalid value for `target_workflow_status` ({0}), must be one of {1}"  # noqa: E501
                .format(target_workflow_status, allowed_values)
            )

        self._target_workflow_status = target_workflow_status

    @property
    def request_id(self):
        """Gets the request_id of this SignalResponse.  # noqa: E501


        :return: The request_id of this SignalResponse.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this SignalResponse.


        :param request_id: The request_id of this SignalResponse.  # noqa: E501
        :type: str
        """

        self._request_id = request_id

    @property
    def workflow_id(self):
        """Gets the workflow_id of this SignalResponse.  # noqa: E501


        :return: The workflow_id of this SignalResponse.  # noqa: E501
        :rtype: str
        """
        return self._workflow_id

    @workflow_id.setter
    def workflow_id(self, workflow_id):
        """Sets the workflow_id of this SignalResponse.


        :param workflow_id: The workflow_id of this SignalResponse.  # noqa: E501
        :type: str
        """

        self._workflow_id = workflow_id

    @property
    def correlation_id(self):
        """Gets the correlation_id of this SignalResponse.  # noqa: E501


        :return: The correlation_id of this SignalResponse.  # noqa: E501
        :rtype: str
        """
        return self._correlation_id

    @correlation_id.setter
    def correlation_id(self, correlation_id):
        """Sets the correlation_id of this SignalResponse.


        :param correlation_id: The correlation_id of this SignalResponse.  # noqa: E501
        :type: str
        """

        self._correlation_id = correlation_id

    @property
    def input(self):
        """Gets the input of this SignalResponse.  # noqa: E501


        :return: The input of this SignalResponse.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this SignalResponse.


        :param input: The input of this SignalResponse.  # noqa: E501
        :type: dict(str, object)
        """

        self._input = input

    @property
    def output(self):
        """Gets the output of this SignalResponse.  # noqa: E501


        :return: The output of this SignalResponse.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this SignalResponse.


        :param output: The output of this SignalResponse.  # noqa: E501
        :type: dict(str, object)
        """

        self._output = output

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SignalResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SignalResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other