import pprint
import re  # noqa: F401

import six

class TerminateWorkflow(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'termination_reason': 'str',
        'workflow_id': 'str'
    }

    attribute_map = {
        'termination_reason': 'terminationReason',
        'workflow_id': 'workflowId'
    }

    def __init__(self, termination_reason=None, workflow_id=None):  # noqa: E501
        """TerminateWorkflow - a model defined in Swagger"""  # noqa: E501
        self._termination_reason = None
        self._workflow_id = None
        self.discriminator = None
        if termination_reason is not None:
            self.termination_reason = termination_reason
        if workflow_id is not None:
            self.workflow_id = workflow_id

    @property
    def termination_reason(self):
        """Gets the termination_reason of this TerminateWorkflow.  # noqa: E501


        :return: The termination_reason of this TerminateWorkflow.  # noqa: E501
        :rtype: str
        """
        return self._termination_reason

    @termination_reason.setter
    def termination_reason(self, termination_reason):
        """Sets the termination_reason of this TerminateWorkflow.


        :param termination_reason: The termination_reason of this TerminateWorkflow.  # noqa: E501
        :type: str
        """

        self._termination_reason = termination_reason

    @property
    def workflow_id(self):
        """Gets the workflow_id of this TerminateWorkflow.  # noqa: E501


        :return: The workflow_id of this TerminateWorkflow.  # noqa: E501
        :rtype: str
        """
        return self._workflow_id

    @workflow_id.setter
    def workflow_id(self, workflow_id):
        """Sets the workflow_id of this TerminateWorkflow.


        :param workflow_id: The workflow_id of this TerminateWorkflow.  # noqa: E501
        :type: str
        """

        self._workflow_id = workflow_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TerminateWorkflow, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TerminateWorkflow):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
