import pprint
import re  # noqa: F401
import six
from dataclasses import dataclass, field, InitVar
from typing import List, Optional
from deprecated import deprecated


@dataclass
class WorkflowSchedule:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    name: Optional[str] = field(default=None)
    cron_expression: Optional[str] = field(default=None)
    run_catchup_schedule_instances: Optional[bool] = field(default=None)
    paused: Optional[bool] = field(default=None)
    start_workflow_request: Optional['StartWorkflowRequest'] = field(default=None)
    schedule_start_time: Optional[int] = field(default=None)
    schedule_end_time: Optional[int] = field(default=None)
    create_time: Optional[int] = field(default=None)
    updated_time: Optional[int] = field(default=None)
    created_by: Optional[str] = field(default=None)
    updated_by: Optional[str] = field(default=None)
    zone_id: Optional[str] = field(default=None)
    tags: Optional[List['Tag']] = field(default=None)
    paused_reason: Optional[str] = field(default=None)
    description: Optional[str] = field(default=None)

    # Private backing fields for properties
    _name: Optional[str] = field(init=False, repr=False, default=None)
    _cron_expression: Optional[str] = field(init=False, repr=False, default=None)
    _run_catchup_schedule_instances: Optional[bool] = field(init=False, repr=False, default=None)
    _paused: Optional[bool] = field(init=False, repr=False, default=None)
    _start_workflow_request: Optional['StartWorkflowRequest'] = field(init=False, repr=False, default=None)
    _schedule_start_time: Optional[int] = field(init=False, repr=False, default=None)
    _schedule_end_time: Optional[int] = field(init=False, repr=False, default=None)
    _create_time: Optional[int] = field(init=False, repr=False, default=None)
    _updated_time: Optional[int] = field(init=False, repr=False, default=None)
    _created_by: Optional[str] = field(init=False, repr=False, default=None)
    _updated_by: Optional[str] = field(init=False, repr=False, default=None)
    _zone_id: Optional[str] = field(init=False, repr=False, default=None)
    _tags: Optional[List['Tag']] = field(init=False, repr=False, default=None)
    _paused_reason: Optional[str] = field(init=False, repr=False, default=None)
    _description: Optional[str] = field(init=False, repr=False, default=None)

    swagger_types = {
        'name': 'str',
        'cron_expression': 'str',
        'run_catchup_schedule_instances': 'bool',
        'paused': 'bool',
        'start_workflow_request': 'StartWorkflowRequest',
        'schedule_start_time': 'int',
        'schedule_end_time': 'int',
        'create_time': 'int',
        'updated_time': 'int',
        'created_by': 'str',
        'updated_by': 'str',
        'zone_id': 'str',
        'tags': 'list[Tag]',
        'paused_reason': 'str',
        'description': 'str'
    }

    attribute_map = {
        'name': 'name',
        'cron_expression': 'cronExpression',
        'run_catchup_schedule_instances': 'runCatchupScheduleInstances',
        'paused': 'paused',
        'start_workflow_request': 'startWorkflowRequest',
        'schedule_start_time': 'scheduleStartTime',
        'schedule_end_time': 'scheduleEndTime',
        'create_time': 'createTime',
        'updated_time': 'updatedTime',
        'created_by': 'createdBy',
        'updated_by': 'updatedBy',
        'zone_id': 'zoneId',
        'tags': 'tags',
        'paused_reason': 'pausedReason',
        'description': 'description'
    }

    def __init__(self, name=None, cron_expression=None, run_catchup_schedule_instances=None, paused=None,
                 start_workflow_request=None, schedule_start_time=None, schedule_end_time=None, create_time=None,
                 updated_time=None, created_by=None, updated_by=None, zone_id=None, tags=None, paused_reason=None,
                 description=None):  # noqa: E501
        """WorkflowSchedule - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._cron_expression = None
        self._run_catchup_schedule_instances = None
        self._paused = None
        self._start_workflow_request = None
        self._schedule_start_time = None
        self._schedule_end_time = None
        self._create_time = None
        self._updated_time = None
        self._created_by = None
        self._updated_by = None
        self._zone_id = None
        self._tags = None
        self._paused_reason = None
        self._description = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if cron_expression is not None:
            self.cron_expression = cron_expression
        if run_catchup_schedule_instances is not None:
            self.run_catchup_schedule_instances = run_catchup_schedule_instances
        if paused is not None:
            self.paused = paused
        if start_workflow_request is not None:
            self.start_workflow_request = start_workflow_request
        if schedule_start_time is not None:
            self.schedule_start_time = schedule_start_time
        if schedule_end_time is not None:
            self.schedule_end_time = schedule_end_time
        if create_time is not None:
            self.create_time = create_time
        if updated_time is not None:
            self.updated_time = updated_time
        if created_by is not None:
            self.created_by = created_by
        if updated_by is not None:
            self.updated_by = updated_by
        if zone_id is not None:
            self.zone_id = zone_id
        if tags is not None:
            self.tags = tags
        if paused_reason is not None:
            self.paused_reason = paused_reason
        if description is not None:
            self.description = description

    def __post_init__(self):
        """Post initialization for dataclass"""
        # Set the dataclass fields to the property backing fields
        if self.name is not None:
            self._name = self.name
        if self.cron_expression is not None:
            self._cron_expression = self.cron_expression
        if self.run_catchup_schedule_instances is not None:
            self._run_catchup_schedule_instances = self.run_catchup_schedule_instances
        if self.paused is not None:
            self._paused = self.paused
        if self.start_workflow_request is not None:
            self._start_workflow_request = self.start_workflow_request
        if self.schedule_start_time is not None:
            self._schedule_start_time = self.schedule_start_time
        if self.schedule_end_time is not None:
            self._schedule_end_time = self.schedule_end_time
        if self.create_time is not None:
            self._create_time = self.create_time
        if self.updated_time is not None:
            self._updated_time = self.updated_time
        if self.created_by is not None:
            self._created_by = self.created_by
        if self.updated_by is not None:
            self._updated_by = self.updated_by
        if self.zone_id is not None:
            self._zone_id = self.zone_id
        if self.tags is not None:
            self._tags = self.tags
        if self.paused_reason is not None:
            self._paused_reason = self.paused_reason
        if self.description is not None:
            self._description = self.description

    @property
    def name(self):
        """Gets the name of this WorkflowSchedule.  # noqa: E501


        :return: The name of this WorkflowSchedule.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WorkflowSchedule.


        :param name: The name of this WorkflowSchedule.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def cron_expression(self):
        """Gets the cron_expression of this WorkflowSchedule.  # noqa: E501


        :return: The cron_expression of this WorkflowSchedule.  # noqa: E501
        :rtype: str
        """
        return self._cron_expression

    @cron_expression.setter
    def cron_expression(self, cron_expression):
        """Sets the cron_expression of this WorkflowSchedule.


        :param cron_expression: The cron_expression of this WorkflowSchedule.  # noqa: E501
        :type: str
        """

        self._cron_expression = cron_expression

    @property
    def run_catchup_schedule_instances(self):
        """Gets the run_catchup_schedule_instances of this WorkflowSchedule.  # noqa: E501


        :return: The run_catchup_schedule_instances of this WorkflowSchedule.  # noqa: E501
        :rtype: bool
        """
        return self._run_catchup_schedule_instances

    @run_catchup_schedule_instances.setter
    def run_catchup_schedule_instances(self, run_catchup_schedule_instances):
        """Sets the run_catchup_schedule_instances of this WorkflowSchedule.


        :param run_catchup_schedule_instances: The run_catchup_schedule_instances of this WorkflowSchedule.  # noqa: E501
        :type: bool
        """

        self._run_catchup_schedule_instances = run_catchup_schedule_instances

    @property
    def paused(self):
        """Gets the paused of this WorkflowSchedule.  # noqa: E501


        :return: The paused of this WorkflowSchedule.  # noqa: E501
        :rtype: bool
        """
        return self._paused

    @paused.setter
    def paused(self, paused):
        """Sets the paused of this WorkflowSchedule.


        :param paused: The paused of this WorkflowSchedule.  # noqa: E501
        :type: bool
        """

        self._paused = paused

    @property
    def start_workflow_request(self):
        """Gets the start_workflow_request of this WorkflowSchedule.  # noqa: E501


        :return: The start_workflow_request of this WorkflowSchedule.  # noqa: E501
        :rtype: StartWorkflowRequest
        """
        return self._start_workflow_request

    @start_workflow_request.setter
    def start_workflow_request(self, start_workflow_request):
        """Sets the start_workflow_request of this WorkflowSchedule.


        :param start_workflow_request: The start_workflow_request of this WorkflowSchedule.  # noqa: E501
        :type: StartWorkflowRequest
        """

        self._start_workflow_request = start_workflow_request

    @property
    def schedule_start_time(self):
        """Gets the schedule_start_time of this WorkflowSchedule.  # noqa: E501


        :return: The schedule_start_time of this WorkflowSchedule.  # noqa: E501
        :rtype: int
        """
        return self._schedule_start_time

    @schedule_start_time.setter
    def schedule_start_time(self, schedule_start_time):
        """Sets the schedule_start_time of this WorkflowSchedule.


        :param schedule_start_time: The schedule_start_time of this WorkflowSchedule.  # noqa: E501
        :type: int
        """

        self._schedule_start_time = schedule_start_time

    @property
    def schedule_end_time(self):
        """Gets the schedule_end_time of this WorkflowSchedule.  # noqa: E501


        :return: The schedule_end_time of this WorkflowSchedule.  # noqa: E501
        :rtype: int
        """
        return self._schedule_end_time

    @schedule_end_time.setter
    def schedule_end_time(self, schedule_end_time):
        """Sets the schedule_end_time of this WorkflowSchedule.


        :param schedule_end_time: The schedule_end_time of this WorkflowSchedule.  # noqa: E501
        :type: int
        """

        self._schedule_end_time = schedule_end_time

    @property
    def create_time(self):
        """Gets the create_time of this WorkflowSchedule.  # noqa: E501


        :return: The create_time of this WorkflowSchedule.  # noqa: E501
        :rtype: int
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this WorkflowSchedule.


        :param create_time: The create_time of this WorkflowSchedule.  # noqa: E501
        :type: int
        """

        self._create_time = create_time

    @property
    def updated_time(self):
        """Gets the updated_time of this WorkflowSchedule.  # noqa: E501


        :return: The updated_time of this WorkflowSchedule.  # noqa: E501
        :rtype: int
        """
        return self._updated_time

    @updated_time.setter
    def updated_time(self, updated_time):
        """Sets the updated_time of this WorkflowSchedule.


        :param updated_time: The updated_time of this WorkflowSchedule.  # noqa: E501
        :type: int
        """

        self._updated_time = updated_time

    @property
    def created_by(self):
        """Gets the created_by of this WorkflowSchedule.  # noqa: E501


        :return: The created_by of this WorkflowSchedule.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this WorkflowSchedule.


        :param created_by: The created_by of this WorkflowSchedule.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def updated_by(self):
        """Gets the updated_by of this WorkflowSchedule.  # noqa: E501


        :return: The updated_by of this WorkflowSchedule.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this WorkflowSchedule.


        :param updated_by: The updated_by of this WorkflowSchedule.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    @property
    def zone_id(self):
        """Gets the zone_id of this WorkflowSchedule.  # noqa: E501


        :return: The zone_id of this WorkflowSchedule.  # noqa: E501
        :rtype: str
        """
        return self._zone_id

    @zone_id.setter
    def zone_id(self, zone_id):
        """Sets the zone_id of this WorkflowSchedule.


        :param zone_id: The zone_id of this WorkflowSchedule.  # noqa: E501
        :type: str
        """

        self._zone_id = zone_id

    @property
    def tags(self):
        """Gets the tags of this WorkflowSchedule.  # noqa: E501


        :return: The tags of this WorkflowSchedule.  # noqa: E501
        :rtype: List[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this WorkflowSchedule.


        :param tags: The tags of this WorkflowSchedule.  # noqa: E501
        :type: List[Tag]
        """

        self._tags = tags

    @property
    def paused_reason(self):
        """Gets the paused_reason of this WorkflowSchedule.  # noqa: E501


        :return: The paused_reason of this WorkflowSchedule.  # noqa: E501
        :rtype: str
        """
        return self._paused_reason

    @paused_reason.setter
    def paused_reason(self, paused_reason):
        """Sets the paused_reason of this WorkflowSchedule.


        :param paused_reason: The paused_reason of this WorkflowSchedule.  # noqa: E501
        :type: str
        """

        self._paused_reason = paused_reason

    @property
    def description(self):
        """Gets the description of this WorkflowSchedule.  # noqa: E501


        :return: The description of this WorkflowSchedule.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this WorkflowSchedule.


        :param description: The description of this WorkflowSchedule.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkflowSchedule, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowSchedule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other